# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-12-18 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_chat_session',
            name='status',
            field=models.CharField(max_length=1),
        ),
    ]
