# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-12-19 07:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_auto_20181218_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_chat_session',
            name='action_user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_taken_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
