# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-12-17 13:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_post', '0002_user_bookmark_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_bookmark_problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quest_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_post.user_problem')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
